# Generated by Django 3.2.9 on 2021-12-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('M_name', models.CharField(blank='True', max_length=30, null='False')),
                ('M_type', models.CharField(max_length=10, null=True)),
                ('Mnf_Date', models.DateField(null=True)),
                ('Exp_Date', models.DateField(null=True)),
                ('MRP', models.FloatField(null=True)),
                ('Stock', models.IntegerField(null=True)),
            ],
        ),
    ]
