# Generated by Django 3.2.9 on 2021-12-15 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='M_name',
            new_name='M_Name',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='M_type',
            new_name='M_Type',
        ),
        migrations.AddField(
            model_name='medicine',
            name='Id',
            field=models.IntegerField(null=True),
        ),
    ]
