# Generated by Django 3.2.9 on 2021-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_remove_medicine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Id',
            field=models.IntegerField(null=True),
        ),
    ]
