# Generated by Django 3.2.9 on 2021-12-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='Exp_Date',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='Mnf_Date',
            field=models.TextField(null=True),
        ),
    ]
