# Generated by Django 3.2.9 on 2021-12-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_auto_20211216_0957'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='Id',
            new_name='S_No',
        ),
        migrations.AlterField(
            model_name='medicine',
            name='M_Name',
            field=models.TextField(blank='True', null='False'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='M_Type',
            field=models.TextField(null=True),
        ),
    ]
