# Generated by Django 3.2.9 on 2021-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0007_auto_20211216_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='S_No',
            field=models.DateField(null=True),
        ),
    ]
