# Generated by Django 3.2.9 on 2021-12-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0008_alter_medicine_s_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='S_No',
        ),
        migrations.AddField(
            model_name='medicine',
            name='Id',
            field=models.IntegerField(null=True),
        ),
    ]
